- hosts: keycloak
  tasks:
    - name: Check keycloak service status
      service:
        name: keycloak
        state: started
      register: keycloak_status

- hosts: cassandra  
  tasks:
    - name: Check Cassandra service status
      service:
        name: cassandra
        state: started
      register: cassandra_status
      
- hosts: lp-neo4j-ps
  tasks:
    - name: Check Neo4j Service Status
      command: "/home/learning/neo4j-learning/neo4j-community-3.3.9/bin/neo4j status"
      register: service_status
      changed_when: false
      become: true

- hosts: composite-search-cluster
  tasks:
    - name: Check Elasticsearch Port
      command: "nc -z -v -w 2 {{ inventory_hostname }} 9200"
      ignore_errors: yes
      register: nc_result      

- hosts: lp-redis-ps
  tasks:
    - name: Check redis service status
      service:
        name: redis
        state: started
      register: redis_status

- hosts: kafka
  tasks:
    - name: Check kafka service status
      service:
        name: kafka
        state: started
      register: kafka_status

- hosts: lp-learning-ps
  tasks:
    - name: Check Tomcat Port (learning VM)
      command: "nc -z -v -w 2 {{ inventory_hostname }} 8080"
      ignore_errors: yes
      register: nc_tomcat_result

# - hosts: internal-proxy
#   tasks:
#     - name: Check Kong Port (Internal proxy)
#       command: "nc -z -v -w 2 {{ inventory_hostname }} 8000"
#       ignore_errors: yes
#       register: nc_kong_result
      
