- hosts: local
  become: yes
  gather_facts: no
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  environment:
        AZURE_STORAGE_ACCOUNT: "{{ sunbird_public_storage_account_name }}"
        AZURE_STORAGE_SAS_TOKEN: "{{ sunbird_public_storage_account_sas  }}"
  tasks:
    - name: rename env_domain in preview_cdn.html for CDN
      shell: |
        echo "{{sunbird_portal_preview_cdn_url}}"
        sed -i 's|cdn_url|{{sunbird_portal_preview_cdn_url}}|g' "{{currentws}}"/ansible/preview/preview_cdn.html
      when: sunbird_portal_preview_cdn_url is defined
      tags:
        - preview

    - name: delete batch
      command: "oci os object bulk-delete -ns {{ sunbird_public_storage_account_name }} -bn {{ plugin_container_name }} --prefix {{ folder_name }}/ --force"
      async: 3600
      poll: 10
      tags:
        - content-editor
        - collection-editor
        - generic-editor
        - preview

    - name: upload batch
      command: "oci os object bulk-upload -bn {{ plugin_container_name }} --prefix {{ folder_name }}/ --src-dir {{ source_name }} --content-type auto"
      async: 3600
      poll: 10
      tags:
        - content-editor 
        - collection-editor
        - generic-editor
        - preview
        - editor
        - core-plugins
  

    - name: upload file
      command: "oci os object put --bucket-name {{ plugin_container_name }} --file {{ source_file_name }} --name artefacts/content-player/content-player-{{ player_version_number }}.zip"
      async: 3600
      poll: 10  
      tags:
        - preview

    - name:  run oci_copy.sh
      shell: "bash {{ oci_file_path }} {{ plugin_container_name }} {{ source_file }} {{ sunbird_public_storage_account_name }}"
      async: 3600
      poll: 10
      tags:
        - plugins
